import XCTest
import CoreLocation
@testable import Listkomat

final class PragueVehicleSourceTests: XCTestCase {
    // Five real vehicles (one per route_type) exactly as the proxy emits them —
    // generated by running the Worker's transform() on a captured Golemio sample.
    private let fixture = """
    {"ts":"2026-07-13T22:10:20+02:00","vehicles":[
      {"id":"10_14927_260418","lat":50.1045,"lng":14.47317,"brng":354,"line":"10","rt":0,"ts":"2026-07-13T22:10:15+02:00","dest":"Sídliště Ďáblice"},
      {"id":"991_11435_260202","lat":50.077774,"lng":14.477781,"brng":293,"line":"A","rt":1,"ts":"2026-07-13T22:10:10+02:00","dest":"Nemocnice Motol"},
      {"id":"1001_8650_251214","lat":50.09727,"lng":14.5441628,"brng":295,"line":"S1","rt":2,"ts":"2026-07-13T22:09:46+02:00","dest":"Praha Masarykovo nádraží"},
      {"id":"100_867_250630","lat":50.10538,"lng":14.28761,"brng":340,"line":"100","rt":3,"ts":"2026-07-13T22:10:10+02:00","dest":"Letiště / Airport ✈"},
      {"id":"58_1837_250714","lat":50.15118,"lng":14.53095,"brng":335,"line":"58","rt":11,"ts":"2026-07-13T22:09:51+02:00","dest":"Miškovice"}
    ]}
    """

    private var fixtureData: Data { Data(fixture.utf8) }
    private let fixtureNow = ISO8601DateFormatter().date(from: "2026-07-13T22:10:20+02:00")!

    func testKindMapping() {
        XCTAssertEqual(PragueVehicleSource.kind(forRouteType: 0), .tram)
        XCTAssertEqual(PragueVehicleSource.kind(forRouteType: 1), .metro)
        XCTAssertEqual(PragueVehicleSource.kind(forRouteType: 2), .train)
        XCTAssertEqual(PragueVehicleSource.kind(forRouteType: 3), .bus)
        XCTAssertEqual(PragueVehicleSource.kind(forRouteType: 11), .trolleybus)
        XCTAssertEqual(PragueVehicleSource.kind(forRouteType: 99), .bus)
    }

    func testDecodeFixture() throws {
        let vs = try PragueVehicleSource.decode(fixtureData)
        XCTAssertEqual(vs.count, 5)

        let metro = try XCTUnwrap(vs.first { $0.kind == .metro })
        XCTAssertEqual(metro.line, "A")
        XCTAssertEqual(metro.destinationName, "Nemocnice Motol")
        XCTAssertNil(metro.destinationId)
        XCTAssertEqual(metro.id, "991_11435_260202")
        XCTAssertEqual(metro.coordinate.latitude, 50.077774, accuracy: 1e-6)
        XCTAssertEqual(metro.coordinate.longitude, 14.477781, accuracy: 1e-6)
        XCTAssertEqual(metro.bearing, 293)

        let train = try XCTUnwrap(vs.first { $0.kind == .train })
        XCTAssertEqual(train.line, "S1")
    }

    func testBboxDropsOutOfArea() throws {
        // Shift nothing but use a box that excludes everything east of Prague.
        let tiny = PragueVehicleSource.BoundingBox(minLat: 0, maxLat: 1, minLng: 0, maxLng: 1)
        let vs = try PragueVehicleSource.decode(fixtureData, bbox: tiny, now: fixtureNow)
        XCTAssertTrue(vs.isEmpty)
    }

    func testFreshnessDropsStale() throws {
        // 60 s window vs fixture timestamps ~10–34 s before `now` keeps all;
        // a `now` far in the future drops all.
        let kept = try PragueVehicleSource.decode(fixtureData, fresherThan: 60, now: fixtureNow)
        XCTAssertEqual(kept.count, 5)
        let future = fixtureNow.addingTimeInterval(3600)
        let dropped = try PragueVehicleSource.decode(fixtureData, fresherThan: 60, now: future)
        XCTAssertTrue(dropped.isEmpty)
    }
}
